/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any[];
};

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Allow the service worker to take control of the page immediately
self.skipWaiting();
clientsClaim();

// --- Firebase Cloud Messaging (FCM) Logic ---

importScripts("https://www.gstatic.com/firebasejs/9.0.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/9.0.0/firebase-messaging-compat.js");

const firebaseConfig = {
  apiKey: "AIzaSyCbKyQS1sppOeWx6mf5mKWRC740AgEgqrM",
  authDomain: "gurukul-library-management.firebaseapp.com",
  projectId: "gurukul-library-management",
  storageBucket: "gurukul-library-management.firebasestorage.app",
  messagingSenderId: "204062876828",
  appId: "1:204062876828:web:702e413d9bd09c10e7b959"
};

// @ts-ignore
firebase.initializeApp(firebaseConfig);
// @ts-ignore
const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload: any) {
  console.log("[sw.ts] 🔔 Background Message Received!");
  
  const title = payload.notification?.title || payload.data?.title || "New Library Notification";
  const body = payload.notification?.body || payload.data?.body || "Check the app for details";
  
  const notificationOptions = {
    body: body,
    icon: "/icon-192.png",
    badge: "/icon-192.png",
    data: payload.data,
    tag: payload.notification?.tag || payload.data?.tag || 'registry-notification',
    renotify: true,
    vibrate: [200, 100, 200]
  };

  return self.registration.showNotification(title, notificationOptions);
});

// Handle notification click
self.addEventListener('notificationclick', function(event: any) {
  event.notification.close();

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList: any) {
      for (let i = 0; i < clientList.length; i++) {
        let client = clientList[i];
        if ('focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow('/dashboard');
      }
    })
  );
});
